# Generated by Django 5.2 on 2026-02-27 05:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.CharField(choices=[('BOOKING', 'Booking'), ('SUBSCRIPTION', 'Subscription'), ('DOCUMENT', 'Document')], max_length=20)),
                ('reference_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='INITIATED', max_length=20)),
                ('gateway', models.CharField(choices=[('FAKE', 'Fake'), ('RAZORPAY', 'Razorpay')], default='FAKE', max_length=20)),
                ('gateway_order_id', models.CharField(blank=True, help_text='Order ID from payment gateway', max_length=100, null=True)),
                ('gateway_payment_id', models.CharField(blank=True, help_text='Payment ID from payment gateway', max_length=100, null=True)),
                ('gateway_response', models.JSONField(blank=True, help_text='Raw gateway response for debugging/audit', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
