# Generated by Django 5.2 on 2025-12-26 07:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.CharField(choices=[('BOOKING', 'Booking'), ('SUBSCRIPTION', 'Subscription'), ('DOCUMENT', 'Document')], max_length=20)),
                ('reference_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='INITIATED', max_length=20)),
                ('gateway', models.CharField(choices=[('FAKE', 'Fake'), ('RAZORPAY', 'Razorpay')], default='FAKE', max_length=20)),
                ('gateway_order_id', models.CharField(blank=True, help_text='Order ID from payment gateway', max_length=100, null=True)),
                ('gateway_payment_id', models.CharField(blank=True, help_text='Payment ID from payment gateway', max_length=100, null=True)),
                ('gateway_response', models.JSONField(blank=True, help_text='Raw gateway response for debugging/audit', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='payments_pa_user_id_01767a_idx'), models.Index(fields=['purpose', 'reference_id'], name='payments_pa_purpose_d6fc18_idx'), models.Index(fields=['gateway'], name='payments_pa_gateway_dc3f0f_idx')],
            },
        ),
    ]
