# Generated by Django 5.2 on 2026-03-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('BOOKING', 'Booking'), ('SUBSCRIPTION', 'Subscription'), ('DOCUMENT', 'Document'), ('COMPANY_POST', 'Company Post')], max_length=20),
        ),
    ]
