# Generated by Django 5.2 on 2026-07-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('FAKE', 'Fake'), ('RAZORPAY', 'Razorpay'), ('PAYU', 'PayU')], default='FAKE', max_length=20),
        ),
    ]
