# Generated by Django 5.2 on 2026-03-27 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_investorslot_investorbooking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('ACTIVE', 'Active'), ('ENDED', 'Ended')], db_index=True, default='WAITING', max_length=10)),
                ('sfu_room_name', models.CharField(blank=True, max_length=255)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('auto_cut_scheduled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_rooms_as_advisor', to=settings.AUTH_USER_MODEL)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_room', to='bookings.booking')),
                ('investor_booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_room', to='bookings.investorbooking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_rooms_as_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('RECORDING', 'Recording'), ('UPLOADING', 'Uploading'), ('READY', 'Ready'), ('DELETED', 'Deleted'), ('FAILED', 'Failed')], db_index=True, default='RECORDING', max_length=12)),
                ('cloudinary_public_id', models.CharField(blank=True, max_length=500)),
                ('cloudinary_secure_url', models.CharField(blank=True, max_length=1000)),
                ('egress_id', models.CharField(blank=True, max_length=255)),
                ('local_file_path', models.CharField(blank=True, max_length=500)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('delete_after', models.DateTimeField(db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='calls.callroom')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CallParticipant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('connection_id', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_participations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='calls.callroom')),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='CallNote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_notes', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='calls.callroom')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CallMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='call_files/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size_bytes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_call_messages', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_messages', to='calls.callroom')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='callroom',
            index=models.Index(fields=['status'], name='calls_callr_status_34bfcc_idx'),
        ),
        migrations.AddIndex(
            model_name='callroom',
            index=models.Index(fields=['user', 'status'], name='calls_callr_user_id_0c3a76_idx'),
        ),
        migrations.AddIndex(
            model_name='callroom',
            index=models.Index(fields=['advisor', 'status'], name='calls_callr_advisor_61bfec_idx'),
        ),
        migrations.AddIndex(
            model_name='callroom',
            index=models.Index(fields=['scheduled_end'], name='calls_callr_schedul_a2d924_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecording',
            index=models.Index(fields=['status', 'delete_after'], name='calls_callr_status_8d3e08_idx'),
        ),
        migrations.AddIndex(
            model_name='callparticipant',
            index=models.Index(fields=['room', 'user'], name='calls_callp_room_id_78fcee_idx'),
        ),
        migrations.AddIndex(
            model_name='callnote',
            index=models.Index(fields=['room', 'user'], name='calls_calln_room_id_cd1ea3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='callnote',
            unique_together={('room', 'user')},
        ),
        migrations.AddIndex(
            model_name='callmessage',
            index=models.Index(fields=['room', 'created_at'], name='calls_callm_room_id_c70945_idx'),
        ),
    ]
