# Generated by Django 5.2 on 2026-07-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_callroom_slot_alter_callroom_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='callroom',
            name='chat_blocked_user_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
