# Generated by Django 5.2 on 2026-07-25 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_callroom_chat_blocked_user_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecording',
            name='error_message',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='RecordingEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('TRIGGERED', 'Triggered'), ('EGRESS_STARTED', 'Egress started'), ('EGRESS_START_FAILED', 'Egress start failed'), ('EGRESS_ENDED', 'Egress ended'), ('EGRESS_FAILED', 'Egress failed'), ('UPLOAD_STARTED', 'Upload started'), ('UPLOAD_COMPLETE', 'Upload complete'), ('UPLOAD_FAILED', 'Upload failed')], db_index=True, max_length=24)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='calls.callrecording')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recording_events', to='calls.callroom')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['room', 'created_at'], name='calls_recor_room_id_99fc3f_idx')],
            },
        ),
    ]
