# Generated by Django 5.2 on 2026-09-28 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_callrecording_error_message_recordingevent'),
        ('meetings', '0002_meeting_allow_guests_meetingguest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='callmessage',
            name='guest_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_call_messages', to='meetings.meetingguest'),
        ),
        migrations.AddField(
            model_name='callparticipant',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_participations', to='meetings.meetingguest'),
        ),
        migrations.AlterField(
            model_name='callmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_call_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='callparticipant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_participations', to=settings.AUTH_USER_MODEL),
        ),
    ]
