# Generated by Django 5.2 on 2025-12-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='admin_review_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='application_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
