# Generated by Django 5.2 on 2026-08-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=10)),
                ('category', models.CharField(choices=[('AUTH', 'Auth'), ('PAYMENT', 'Payment'), ('BOOKING', 'Booking'), ('CALL', 'Call / Recording'), ('CHAT', 'Chat'), ('COMMUNITY', 'Community'), ('NOTIFICATION', 'Notification'), ('ADMIN', 'Admin'), ('SYSTEM', 'System')], db_index=True, default='SYSTEM', max_length=20)),
                ('logger_name', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', 'created_at'], name='adminpanel__level_a70cbe_idx'), models.Index(fields=['category', 'created_at'], name='adminpanel__categor_ec0ff5_idx')],
            },
        ),
    ]
