# Generated by Django 5.2 on 2026-03-02 11:04

import ads.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], editable=False, max_length=10)),
                ('file', models.FileField(upload_to=ads.models.ad_media_upload_path)),
                ('redirect_url', models.URLField()),
                ('button_text', models.CharField(default='Learn More', max_length=50)),
                ('placement', models.CharField(choices=[('sidebar_featured', 'Sidebar Featured Partner')], db_index=True, default='sidebar_featured', max_length=50)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['placement', 'is_active'], name='ads_adverti_placeme_f84cba_idx'), models.Index(fields=['start_datetime', 'end_datetime'], name='ads_adverti_start_d_8c7796_idx')],
            },
        ),
    ]
