# Generated by Django 5.2 on 2026-02-27 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='expert',
            field=models.ForeignKey(limit_choices_to={'user_type': 'expert'}, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_expert', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user',
            field=models.ForeignKey(limit_choices_to={'user_type': 'normal'}, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readreceipt',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='chat.message'),
        ),
        migrations.AddField(
            model_name='readreceipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['user', 'expert'], name='chat_chatro_user_id_6d5cee_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['last_message_at'], name='chat_chatro_last_me_81d745_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('user', 'expert')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'timestamp'], name='chat_messag_room_id_645da7_idx'),
        ),
        migrations.AddIndex(
            model_name='readreceipt',
            index=models.Index(fields=['message', 'user'], name='chat_readre_message_8f2085_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='readreceipt',
            unique_together={('message', 'user')},
        ),
    ]
