# Generated by Django 5.2 on 2025-12-29 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='full_content',
            field=models.TextField(blank=True, help_text='Visible only to premium users', max_length=5000),
        ),
        migrations.AddField(
            model_name='comment',
            name='preview_content',
            field=models.TextField(blank=True, help_text='Visible to all users', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='full_content',
            field=models.TextField(blank=True, help_text='Visible only to premium users', max_length=10000),
        ),
        migrations.AddField(
            model_name='post',
            name='preview_content',
            field=models.TextField(blank=True, help_text='Visible to all users (non-premium)', max_length=3000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Null = top-level comment, Not null = reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.comment'),
        ),
    ]
