# Generated by Django 5.2 on 2026-07-25 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_post_fulltext_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='hidden_by',
            field=models.ForeignKey(blank=True, help_text='Admin who hid this post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False, help_text='Hidden from the public feed by a moderator (soft removal).'),
        ),
        migrations.AddField(
            model_name='post',
            name='moderation_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_hidden', 'created_at'], name='community_p_is_hidd_6d8422_idx'),
        ),
    ]
