# Generated by Django 5.2 on 2026-07-25 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_post_hidden_at_post_hidden_by_post_is_hidden_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='hidden_by',
            field=models.ForeignKey(blank=True, help_text='Admin who hid this comment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False, help_text='Hidden from the public feed by a moderator (soft removal).'),
        ),
        migrations.AddField(
            model_name='comment',
            name='moderation_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_hidden'], name='community_c_is_hidd_7633f6_idx'),
        ),
    ]
