# Generated by Django 5.2 on 2026-01-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_migrate_content_to_preview_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='preview_content',
            field=models.TextField(blank=True, help_text='Visible to all users', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview_content',
            field=models.TextField(blank=True, help_text='Visible to all users (non-premium)', max_length=500),
        ),
    ]
