# Generated by Django 5.2 on 2026-02-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_comment_preview_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='knowledge_hub',
            field=models.BooleanField(db_index=True, default=False, help_text='True = Knowledge Hub post (Idea/Structured knowledge post)'),
        ),
    ]
