# Generated by Django 5.2 on 2026-09-28 05:14

import django.db.models.deletion
import meetings.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0004_callrecording_error_message_recordingevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('invite_token', models.CharField(db_index=True, default=meetings.models.generate_invite_token, max_length=64, unique=True)),
                ('access_mode', models.CharField(choices=[('INVITED_ONLY', 'Only invited users'), ('ANYONE_WITH_LINK', 'Anyone with the link')], default='ANYONE_WITH_LINK', max_length=20)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('max_participants', models.PositiveIntegerField(default=20)),
                ('require_host', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('ENDED', 'Ended'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_room', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting', to='calls.callroom')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings_hosted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingInvite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='meetings.meeting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['invited_at'],
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['status', 'scheduled_start'], name='meetings_me_status_535826_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['host', 'status'], name='meetings_me_host_id_939657_idx'),
        ),
        migrations.AddIndex(
            model_name='meetinginvite',
            index=models.Index(fields=['meeting', 'user'], name='meetings_me_meeting_578dc5_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetinginvite',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('meeting', 'user'), name='unique_meeting_invite_per_user'),
        ),
    ]
