# Generated by Django 5.2 on 2026-09-28 05:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='allow_guests',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='MeetingGuest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=60)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='meetings.meeting')),
            ],
            options={
                'ordering': ['joined_at'],
                'indexes': [models.Index(fields=['meeting', 'joined_at'], name='meetings_me_meeting_139a02_idx')],
            },
        ),
    ]
