# Generated by Django 5.2 on 2025-12-02 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StartupStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Startup Stage',
                'verbose_name_plural': 'Startup Stages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(db_index=True, max_length=255)),
                ('one_liner', models.CharField(blank=True, max_length=280)),
                ('investment_thesis', models.TextField(blank=True)),
                ('check_size_min', models.DecimalField(decimal_places=2, help_text='Minimum investment amount in USD', max_digits=15)),
                ('check_size_max', models.DecimalField(decimal_places=2, help_text='Maximum investment amount in USD', max_digits=15)),
                ('location', models.CharField(blank=True, help_text='e.g. San Francisco, CA | London | Singapore', max_length=150)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('investor_type', models.CharField(choices=[('angel', 'Angel Investor'), ('vc', 'VC Firm'), ('fund', 'Investment Fund'), ('family_office', 'Family Office')], db_index=True, max_length=50)),
                ('verified_by_admin', models.BooleanField(db_index=True, default=False)),
                ('application_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_created_investors', to=settings.AUTH_USER_MODEL)),
                ('focus_industries', models.ManyToManyField(blank=True, related_name='investors', to='investors.industry')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
                ('preferred_stages', models.ManyToManyField(blank=True, related_name='investors', to='investors.startupstage')),
            ],
            options={
                'verbose_name': 'Investor',
                'verbose_name_plural': 'Investors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['investor_type'], name='investors_i_investo_4d4bbd_idx'), models.Index(fields=['verified_by_admin'], name='investors_i_verifie_f5e455_idx'), models.Index(fields=['application_status'], name='investors_i_applica_7514e4_idx'), models.Index(fields=['check_size_min'], name='investors_i_check_s_83666f_idx'), models.Index(fields=['check_size_max'], name='investors_i_check_s_d88038_idx')],
                'constraints': [models.UniqueConstraint(fields=('user',), name='unique_investor_per_user')],
            },
        ),
    ]
