# Generated by Django 5.2 on 2026-02-27 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_created_investors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investor',
            name='focus_industries',
            field=models.ManyToManyField(blank=True, related_name='investors', to='investors.industry'),
        ),
        migrations.AddField(
            model_name='investor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investor',
            name='preferred_stages',
            field=models.ManyToManyField(blank=True, related_name='investors', to='investors.startupstage'),
        ),
        migrations.AddIndex(
            model_name='investor',
            index=models.Index(fields=['investor_type'], name='investors_i_investo_4d4bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='investor',
            index=models.Index(fields=['verified_by_admin'], name='investors_i_verifie_f5e455_idx'),
        ),
        migrations.AddIndex(
            model_name='investor',
            index=models.Index(fields=['application_status'], name='investors_i_applica_7514e4_idx'),
        ),
        migrations.AddIndex(
            model_name='investor',
            index=models.Index(fields=['check_size_min'], name='investors_i_check_s_83666f_idx'),
        ),
        migrations.AddIndex(
            model_name='investor',
            index=models.Index(fields=['check_size_max'], name='investors_i_check_s_d88038_idx'),
        ),
        migrations.AddConstraint(
            model_name='investor',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_investor_per_user'),
        ),
    ]
