# Generated by Django 5.2 on 2025-12-30 13:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('access_type', models.CharField(choices=[('FREE', 'Free'), ('PREMIUM', 'Premium'), ('PAID', 'Paid')], default='FREE', help_text='Controls who can access this document', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Disable document without deleting it')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Admin who uploaded this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDownload',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('access_type_snapshot', models.CharField(choices=[('FREE', 'Free'), ('PREMIUM', 'Premium'), ('PAID', 'Paid')], help_text='Access type at the time of download', max_length=10)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-downloaded_at'],
                'indexes': [models.Index(fields=['user', 'downloaded_at'], name='documents_d_user_id_f1cd53_idx'), models.Index(fields=['document'], name='documents_d_documen_a8d0a0_idx')],
            },
        ),
    ]
