# Generated by Django 5.2 on 2026-02-27 05:16

import documents.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('access_type', models.CharField(choices=[('FREE', 'Free'), ('PREMIUM', 'Premium'), ('PAID', 'Paid')], default='FREE', help_text='Controls who can access this document', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Disable document without deleting it')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDownload',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('access_type_snapshot', models.CharField(choices=[('FREE', 'Free'), ('PREMIUM', 'Premium'), ('PAID', 'Paid')], help_text='Access type at the time of download', max_length=10)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_upload_limit', models.PositiveIntegerField(default=5)),
                ('monthly_download_limit', models.PositiveIntegerField(default=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
