# Generated by Django 5.2 on 2026-01-13 09:16

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentdownload',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='documentdownload',
            name='documents_d_user_id_f1cd53_idx',
        ),
        migrations.AddField(
            model_name='documentdownload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='documentdownload',
            index=models.Index(fields=['user', 'created_at'], name='documents_d_user_id_faf59d_idx'),
        ),
    ]
