# Generated by Django 5.2 on 2026-02-27 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentdownload',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentdownload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_downloads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='documentdownload',
            index=models.Index(fields=['user', 'created_at'], name='documents_d_user_id_faf59d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentdownload',
            index=models.Index(fields=['document'], name='documents_d_documen_a8d0a0_idx'),
        ),
    ]
