# Generated by Django 5.2 on 2026-02-25 09:19

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentplatformsettings_alter_document_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=documents.models.document_upload_path),
        ),
    ]
