# Generated by Django 5.2 on 2025-12-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
