# Generated by Django 5.2 on 2025-12-13 07:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0002_expertprofile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertprofile',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
