# Generated by Django 5.2 on 2026-03-16 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companypostsettings'),
        ('payments', '0003_alter_payment_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypost',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companypost',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_posts', to='payments.payment'),
        ),
    ]
