# Generated by Django 5.2 on 2026-02-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='premium_docs_used_this_month',
        ),
    ]
