# Generated by Django 5.2 on 2025-12-24 09:18

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingpayment',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookingpayment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bookingreview',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookingreview',
            name='expert',
        ),
        migrations.RemoveField(
            model_name='bookingreview',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_active_booking_per_slot',
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='decline_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='expertslot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='slotrecurringpattern',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slotrecurringpattern',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slotrecurringpattern',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAID', 'Paid'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=24),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['uuid'], name='bookings_bo_uuid_c3e83d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'created_at'], name='bookings_bo_status_72dd85_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['slot', 'status'], name='bookings_bo_slot_id_b05dec_idx'),
        ),
        migrations.AddIndex(
            model_name='expertslot',
            index=models.Index(fields=['expert', 'status'], name='bookings_ex_expert__0edce7_idx'),
        ),
        migrations.AddIndex(
            model_name='expertslot',
            index=models.Index(fields=['uuid'], name='bookings_ex_uuid_6cfab6_idx'),
        ),
        migrations.AddIndex(
            model_name='slotrecurringpattern',
            index=models.Index(fields=['expert', 'is_active'], name='bookings_sl_expert__540b96_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'AWAITING_PAYMENT', 'PAID', 'CONFIRMED'])), fields=('slot',), name='unique_active_booking_per_slot'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'AWAITING_PAYMENT', 'PAID', 'CONFIRMED', 'COMPLETED'])), fields=('user', 'slot'), name='unique_user_booking_per_slot'),
        ),
        migrations.AddConstraint(
            model_name='expertslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='slot_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='slotrecurringpattern',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='valid_weekday'),
        ),
        migrations.AddConstraint(
            model_name='slotrecurringpattern',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='pattern_end_after_start'),
        ),
        migrations.DeleteModel(
            name='BookingPayment',
        ),
        migrations.DeleteModel(
            name='BookingReview',
        ),
    ]
