# Generated by Django 5.2 on 2026-02-27 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_expert', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expertslot',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.expertslot'),
        ),
        migrations.AddField(
            model_name='slotrecurringpattern',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_patterns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='expertslot',
            index=models.Index(fields=['expert', 'start_datetime'], name='bookings_ex_expert__62b5d4_idx'),
        ),
        migrations.AddIndex(
            model_name='expertslot',
            index=models.Index(fields=['start_datetime'], name='bookings_ex_start_d_fdf5cf_idx'),
        ),
        migrations.AddIndex(
            model_name='expertslot',
            index=models.Index(fields=['expert', 'status'], name='bookings_ex_expert__0edce7_idx'),
        ),
        migrations.AddIndex(
            model_name='expertslot',
            index=models.Index(fields=['uuid'], name='bookings_ex_uuid_6cfab6_idx'),
        ),
        migrations.AddConstraint(
            model_name='expertslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='slot_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='bookings_bo_user_id_69a5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['expert', 'status'], name='bookings_bo_expert__b72c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['start_datetime'], name='bookings_bo_start_d_d047d2_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['uuid'], name='bookings_bo_uuid_c3e83d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'created_at'], name='bookings_bo_status_72dd85_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['slot', 'status'], name='bookings_bo_slot_id_b05dec_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'AWAITING_PAYMENT', 'PAID', 'CONFIRMED'])), fields=('slot',), name='unique_active_booking_per_slot'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'AWAITING_PAYMENT', 'PAID', 'CONFIRMED', 'COMPLETED'])), fields=('user', 'slot'), name='unique_user_booking_per_slot'),
        ),
        migrations.AddIndex(
            model_name='slotrecurringpattern',
            index=models.Index(fields=['expert', 'weekday'], name='bookings_sl_expert__9fed48_idx'),
        ),
        migrations.AddIndex(
            model_name='slotrecurringpattern',
            index=models.Index(fields=['expert', 'is_active'], name='bookings_sl_expert__540b96_idx'),
        ),
        migrations.AddConstraint(
            model_name='slotrecurringpattern',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='valid_weekday'),
        ),
        migrations.AddConstraint(
            model_name='slotrecurringpattern',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='pattern_end_after_start'),
        ),
    ]
