# Generated by Django 5.2 on 2026-03-04 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorSlot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='InvestorBooking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=24)),
                ('reschedule_count', models.PositiveSmallIntegerField(default=0)),
                ('chat_room_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_investor', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_bookings', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.investorslot')),
            ],
        ),
        migrations.AddIndex(
            model_name='investorslot',
            index=models.Index(fields=['investor', 'start_datetime'], name='bookings_in_investo_b57dde_idx'),
        ),
        migrations.AddIndex(
            model_name='investorslot',
            index=models.Index(fields=['investor', 'status'], name='bookings_in_investo_3e3390_idx'),
        ),
        migrations.AddConstraint(
            model_name='investorslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='investor_slot_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='investorbooking',
            index=models.Index(fields=['user', 'created_at'], name='bookings_in_user_id_ac7f3d_idx'),
        ),
        migrations.AddIndex(
            model_name='investorbooking',
            index=models.Index(fields=['investor', 'status'], name='bookings_in_investo_8516f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='investorbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED'])), fields=('slot',), name='unique_active_investor_booking_per_slot'),
        ),
    ]
