# Generated by Django 5.2 on 2026-04-18 05:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_expertslot_session_type_booking_session_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertslot',
            name='video_call_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
