# Generated by Django 5.2 on 2026-07-15 11:32

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_expertslot_video_call_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_active_booking_per_slot',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_batch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expertslot',
            name='batch_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='expertslot',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='expertslot',
            name='slot_mode',
            field=models.CharField(choices=[('ONE_TO_ONE', 'One to One'), ('BATCH', 'Batch (Group Video Call)')], default='ONE_TO_ONE', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('is_batch', False), ('status__in', ['PENDING', 'AWAITING_PAYMENT', 'PAID', 'CONFIRMED'])), fields=('slot',), name='unique_active_booking_per_slot'),
        ),
    ]
