# Generated by Django 5.2 on 2026-08-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_booking_unique_active_booking_per_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertslot',
            name='is_batch_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expertslot',
            name='is_chat_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expertslot',
            name='is_video_call_free',
            field=models.BooleanField(default=False),
        ),
    ]
